import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";
import fs from "fs";

// HTTPS config — serve over https://0.0.0.0:3000 so tablet can access
// Uses self-signed cert generated by PowerShell (server.pfx)
// Set TLS_PASSPHRASE env var (defaults to empty — cert was created with no passphrase)
const sslOptions = fs.existsSync(path.join(__dirname, "server.pfx"))
  ? {
      https: {
        pfx: fs.readFileSync(path.join(__dirname, "server.pfx")),
        passphrase: process.env.TLS_PASSPHRASE || "",
      },
    }
  : {};

export default defineConfig({
  plugins: [react()],
  server: {
    host: true, // expose on LAN
    port: 3000,
    ...sslOptions,
    proxy: {
      "/api": {
        target: "http://localhost:3001",
        changeOrigin: true,
        secure: false,
      },
    },
  },
  preview: {
    host: true,
    port: 4173,
    ...sslOptions,
    proxy: {
      "/api": {
        target: "http://localhost:3001",
        changeOrigin: true,
        secure: false,
      },
    },
  },
  build: {
    outDir: "dist",
    sourcemap: false,
  },
});
